# This is a basic workflow that is manually triggered

name: Blog Website Push Event

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
      branches: ["main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
  # This workflow contains a single job called "greet"
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
         host: ${{ secrets.DAYLINK_HOST }}
         username: ${{ secrets.DAYLINK_USERNAME }}
         password: ${{ secrets.DAYLINK_PASSWORD }}
         port: 22
         script: |
          cd /var/www/html/Next-Node-Blog || exit
          git pull || exit
          cd client || exit
          npm install || exit
          cd .. || exit
          cd server || exit
          npm install || exit
          pm2 restart all || exit
